[build]
  command = "npx nx run myproject:build"
  publish = "dist"

[context.getandrewmortimer]
  command = "npx nx run getandrewmortimer:build:production"
  publish = "dist/getandrewmortimer"

[context.empiricalarchetype]
  command = "npx nx run empiricalarchetype:build:production"
  publish = "dist/empiricalarchetype"
